// MANUALY UPDATED
// WE <3 HANDS

#ifndef LLAMA_CPP_BUILD_NUMBER
#define LLAMA_CPP_BUILD_NUMBER 6434
#endif

#ifndef LLAMA_CPP_VERSION
#define LLAMA_CPP_VERSION "b6434"
#define GGML_VERSION LLAMA_CPP_VERSION
#endif
#ifndef LLAMA_CPP_COMMIT
#define LLAMA_CPP_COMMIT "86587da03bd78df8f4e7d8b111a0c1d2494d6ed0"
#define GGML_COMMIT LLAMA_CPP_COMMIT
#endif